Q1) Write a function so that the columns of the output matrix are powers of the input
    vector.
    The order of the powers is determined by the increasing boolean argument. Specifically, when
    increasing is False, the i-th output column is the input vector raised element-wise to the power
    of N - i - 1.(Alexandre-Theophile Vandermonde Matrix.)

In [1]:
import pandas as pd
import numpy as np
def Vandermonde_Matrix(X,n,increasing= False):
    if not increasing:
        van_mat = np.array([[x**(n-1-i) for i in range(n)] for x in X])
    else:
        van_mat = np.array([[x**i for i in range(n)] for x in X])
    return van_mat   

x= np.array([1, 2, 3, 5])
n= 3
van_dec = Vandermonde_Matrix(x,n,False)
print("in decreasing order: ","\n\n",van_dec,"\n")
van_inc = Vandermonde_Matrix(x,n,True)
print("in increasing order: ","\n\n",van_inc)

in decreasing order:  

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]] 

in increasing order:  

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  5 25]]


Q2) Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [40]:
import pandas as pd
import numpy as np
c=[]
def moving_avg_seq(x,n,k):
    No_of_MAS = n-k+1
    for i in range(0,No_of_MAS):
        y = np.sum(x[i:i+3])/3
        c.append(y)
    print("the moving average sequence")
    return np.array(c).round(2)
       
    
    
x = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
n = x.size
k = 3
moving_avg_seq(x,n,k)    

the moving average sequence


array([  5.  ,   4.67,   5.67,   6.67,   9.67,  28.67,  49.33,  72.67,
        84.  ,  93.33, 116.33])

In [44]:
np.pow(x)

AttributeError: module 'numpy' has no attribute 'pow'